export const types = {
  UPDATE_TOP_LEVEL: 'UPDATE_TOP_LEVEL',
  UPDATE_CONTACT_SHOW_TYPE: 'UPDATE_CONTACT_SHOW_TYPE',
  UPDATE_FRIENDS: 'UPDATE_FRIENDS',
  UPDATE_GROUPS: 'UPDATE_GROUPS',
  UPDATE_SESSIONS: 'UPDATE_SESSIONS',
  SET_ACTIVED_SESSION_ID: 'SET_ACTIVED_SESSION_ID',
  SET_USER_INFO: 'SET_USER_INFO'
};
